package com.busbooking.model;
// Generated May 3, 2018 1:42:29 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Busdealer generated by hbm2java
 */
@Entity
@Table(name = "busdealer", catalog = "busbooking")
public class Busdealer implements java.io.Serializable {

	private Integer id;
	private String agencyname;
	private String arrive;
	private String depart;
	private String fee;
	private String seats;
	private Set<Ticketbook> ticketbooks = new HashSet<Ticketbook>(0);

	public Busdealer() {
	}

	public Busdealer(String agencyname, String arrive, String depart, String fee, String seats,
			Set<Ticketbook> ticketbooks) {
		this.agencyname = agencyname;
		this.arrive = arrive;
		this.depart = depart;
		this.fee = fee;
		this.seats = seats;
		this.ticketbooks = ticketbooks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "agencyname")
	public String getAgencyname() {
		return this.agencyname;
	}

	public void setAgencyname(String agencyname) {
		this.agencyname = agencyname;
	}

	@Column(name = "arrive")
	public String getArrive() {
		return this.arrive;
	}

	public void setArrive(String arrive) {
		this.arrive = arrive;
	}

	@Column(name = "depart")
	public String getDepart() {
		return this.depart;
	}

	public void setDepart(String depart) {
		this.depart = depart;
	}

	@Column(name = "fee")
	public String getFee() {
		return this.fee;
	}

	public void setFee(String fee) {
		this.fee = fee;
	}

	@Column(name = "seats")
	public String getSeats() {
		return this.seats;
	}

	public void setSeats(String seats) {
		this.seats = seats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "busdealer")
	public Set<Ticketbook> getTicketbooks() {
		return this.ticketbooks;
	}

	public void setTicketbooks(Set<Ticketbook> ticketbooks) {
		this.ticketbooks = ticketbooks;
	}

}
