package com.busbooking.model;
// Generated May 3, 2018 1:42:29 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ticketbook generated by hbm2java
 */
@Entity
@Table(name = "ticketbook", catalog = "busbooking")
public class Ticketbook implements java.io.Serializable {

	private Integer bookingid;
	private Busdealer busdealer;
	private String age;
	private Date bookingdate;
	private String destination;
	private String doj;
	private String dor;
	private String email;
	private String mobile;
	private String name;
	private String source;
	private Boolean status = true;

	public Ticketbook() {
	}

	public Ticketbook(Busdealer busdealer, String age, Date bookingdate, String destination, String doj,
			String dor, String email, String mobile, String name, String source, Boolean status) {
		this.busdealer = busdealer;
		this.age = age;
		this.bookingdate = bookingdate;
		this.destination = destination;
		this.doj = doj;
		this.dor = dor;
		this.email = email;
		this.mobile = mobile;
		this.name = name;
		this.source = source;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bookingid", unique = true, nullable = false)
	public Integer getBookingid() {
		return this.bookingid;
	}

	public void setBookingid(Integer bookingid) {
		this.bookingid = bookingid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bus_dealer")
	public Busdealer getBusdealer() {
		return this.busdealer;
	}

	public void setBusdealer(Busdealer busdealer) {
		this.busdealer = busdealer;
	}

	@Column(name = "age")
	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bookingdate", length = 19)
	public Date getBookingdate() {
		return this.bookingdate;
	}

	public void setBookingdate(Date bookingdate) {
		this.bookingdate = bookingdate;
	}

	@Column(name = "destination")
	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	@Column(name = "doj")
	public String getDoj() {
		return this.doj;
	}

	public void setDoj(String doj) {
		this.doj = doj;
	}

	@Column(name = "dor")
	public String getDor() {
		return this.dor;
	}

	public void setDor(String dor) {
		this.dor = dor;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "mobile")
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "source")
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
